s3_paths:
  incoming: s3://my-bucket/incoming
  outgoing: s3://my-bucket/outgoing
  incoming[000]: s3://incoming-000
  incoming[001]: s3://incoming-001
s3_paths[001]:
  incoming: s3://001-incoming
  outgoing[002]: s3://001-outgoing-002
